# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PontosColeta
                                 A QGIS plugin
 Gere pontos aleatórios dentro de feições de forma homogênea
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-31
        copyright            : (C) 2026 by Alex Felipe de Souza
        email                : alexfelipe00@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PontosColeta class from file PontosColeta.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pontos_coleta import PontosColeta
    return PontosColeta(iface)
